// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Darren Ford")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
